default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV["DATABASE_URL"] %>
  pool: 10

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV["DATABASE_URL"] || "postgres://app:app@db:5432/beams_test" %>

production:
  <<: *default
